### ISSUE TITLE
Multiple dependencies incompatible with current nodejs LTS release

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [logdna/logdna-cli#27]
The 1.x version of `bufferutil` in use does not work for node 10.x:
```
make: Entering directory '/home/mgl/3psrc/logdna-cli/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../../nan/nan.h:190:0,
                 from ../src/validation.cc:15:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```

Updating the `bufferutil` and `utf-8-validate` dependency to the current release addresses this, but I don't know if that "works" because it now insists on running as `root`, which is not viable in my environment.

**Comment by smusali** [comment]
Hey @mgabeler-lee-6rs, this `bufferutil` issue is widely known one and right now, it works well on `node@6.10.2` and `npm@6.4.1` - but you are right, it should be fixed universally and `bufferutil` version should be updated from `v1` to `latest` in our `package.json`.

Let me work on and test this! I will let you know here by the end of today!

Thanks again!

**Comment by smusali** [comment]
it's already been fixed!
